import {
  Doctor,
  Patient,
  Appointment,
  WaitingQueueItem,
  Invoice,
  LabTest,
  LabOrder,
  Medicine,
  Bed,
  OperationTheaterBooking,
  Prescription,
  Employee,
} from "@/types";

export const MOCK_ORGANIZATION = {
  id: "a0000000-0000-0000-0000-000000000001",
  name: "Onnesha Hospital & Diagnostic Complex",
  banglaName: "অন্বেষা হাসপাতাল ও ডায়াগনস্টিক কমপ্লেক্স",
  code: "OH",
  phone: "01712-345678",
  emergencyHotline: "01700-112233",
  ambulanceHotline: "01800-445566",
  email: "info@onneshahospital.com",
  address: "Hospital Road, Main Bazar, Dhaka, Bangladesh",
  regNo: "DGHS-REG-2024-8912",
};

export const MOCK_DEPARTMENTS = [
  { id: "dept-1", name: "General Medicine", code: "MED", totalDoctors: 6 },
  { id: "dept-2", name: "Cardiology & Heart Care", code: "CARD", totalDoctors: 4 },
  { id: "dept-3", name: "Gynecology & Obstetrics", code: "GYN", totalDoctors: 5 },
  { id: "dept-4", name: "Pediatrics & Child Health", code: "PED", totalDoctors: 4 },
  { id: "dept-5", name: "Orthopedic Surgery", code: "ORTH", totalDoctors: 3 },
  { id: "dept-6", name: "Pathology & Lab Medicine", code: "PATH", totalDoctors: 2 },
  { id: "dept-7", name: "Radiology & Imaging (X-Ray/USG)", code: "RAD", totalDoctors: 3 },
  { id: "dept-8", name: "Emergency & Critical Care", code: "EMERG", totalDoctors: 8 },
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "doc-1",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_code: "DOC-001",
    full_name: "Prof. Dr. M. A. Rahman",
    specialization: "Senior Medicine Specialist",
    designation: "Professor & Head of Medicine",
    degrees: "MBBS, FCPS (Medicine), MACP (USA)",
    bmdc_reg_number: "A-12490",
    department_id: "dept-1",
    department_name: "General Medicine",
    opd_fee: 800,
    report_followup_fee: 400,
    commission_rate: 20,
    room_number: "Room 101 (1st Floor)",
    avatar_url: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&h=300&fit=crop&crop=face",
    is_active: true,
  },
  {
    id: "doc-2",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_code: "DOC-002",
    full_name: "Dr. Farhana Yasmin",
    specialization: "Gynecologist & Obstetrician",
    designation: "Associate Professor",
    degrees: "MBBS, DGO, FCPS (Gynae & Obs)",
    bmdc_reg_number: "A-23812",
    department_id: "dept-3",
    department_name: "Gynecology & Obstetrics",
    opd_fee: 700,
    report_followup_fee: 300,
    commission_rate: 20,
    room_number: "Room 102 (1st Floor)",
    avatar_url: "https://images.unsplash.com/photo-1594824813579-3075d9e504c5?w=300&h=300&fit=crop&crop=face",
    is_active: true,
  },
  {
    id: "doc-3",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_code: "DOC-003",
    full_name: "Dr. Tanvir Ahmed",
    specialization: "Clinical & Interventional Cardiologist",
    designation: "Consultant Cardiologist",
    degrees: "MBBS, MD (Cardiology), NICVD",
    bmdc_reg_number: "A-31908",
    department_id: "dept-2",
    department_name: "Cardiology",
    opd_fee: 1000,
    report_followup_fee: 500,
    commission_rate: 25,
    room_number: "Room 103 (1st Floor)",
    avatar_url: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&h=300&fit=crop&crop=face",
    is_active: true,
  },
  {
    id: "doc-4",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_code: "DOC-004",
    full_name: "Dr. Kazi Mahfuzur Rahman",
    specialization: "Pediatrician & Newborn Specialist",
    designation: "Assistant Professor (Pediatrics)",
    degrees: "MBBS, DCH, FCPS (Pediatrics)",
    bmdc_reg_number: "A-19834",
    department_id: "dept-4",
    department_name: "Pediatrics & Child Health",
    opd_fee: 600,
    report_followup_fee: 300,
    commission_rate: 20,
    room_number: "Room 104 (1st Floor)",
    avatar_url: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&h=300&fit=crop&crop=face",
    is_active: true,
  },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "pat-1",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "OH-000101",
    full_name: "Md. Rafiqul Islam",
    guardian_name: "Abdul Halim",
    relationship_with_guardian: "Father",
    gender: "male",
    dob: "1982-05-14",
    age: 44,
    blood_group: "B+",
    phone: "01711-223344",
    nid_or_birth_cert: "19822691234567890",
    address: "Village: Shantinagar, Ward 04, Dhaka",
    emergency_contact_name: "Rokeya Begum (Wife)",
    emergency_contact_phone: "01722-334455",
    created_at: "2026-09-01T09:30:00Z",
  },
  {
    id: "pat-2",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "OH-000102",
    full_name: "Nasrin Akhter",
    guardian_name: "Kamal Hossain",
    relationship_with_guardian: "Husband",
    gender: "female",
    dob: "1994-11-20",
    age: 32,
    blood_group: "O+",
    phone: "01819-876543",
    nid_or_birth_cert: "19942691234567891",
    address: "House 24, Road 5, Mirpur, Dhaka",
    emergency_contact_name: "Kamal Hossain",
    emergency_contact_phone: "01819-876543",
    created_at: "2026-09-02T11:15:00Z",
  },
  {
    id: "pat-3",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "OH-000103",
    full_name: "Master Aayan Chowdhury",
    guardian_name: "Kabir Chowdhury",
    relationship_with_guardian: "Father",
    gender: "male",
    dob: "2021-03-10",
    age: 5,
    blood_group: "A+",
    phone: "01912-334455",
    address: "Bypass Road, Dhanmondi, Dhaka",
    emergency_contact_name: "Kabir Chowdhury",
    emergency_contact_phone: "01912-334455",
    created_at: "2026-09-05T14:20:00Z",
  },
  {
    id: "pat-4",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "OH-000104",
    full_name: "Haji Nurul Haque",
    guardian_name: "Late Fazlul Haque",
    relationship_with_guardian: "Father",
    gender: "male",
    dob: "1958-08-12",
    age: 68,
    blood_group: "AB+",
    phone: "01611-998877",
    address: "Central Road, Uttara, Dhaka",
    emergency_contact_name: "Tariqul Haque (Son)",
    emergency_contact_phone: "01611-998800",
    created_at: "2026-09-08T10:00:00Z",
  },
];

export const MOCK_WAITING_QUEUE: WaitingQueueItem[] = [
  {
    id: "q-1",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_id: "doc-1",
    doctor_name: "Prof. Dr. M. A. Rahman",
    room_number: "Room 101",
    appointment_id: "apt-1",
    patient_name: "Md. Rafiqul Islam",
    token_number: "A-012",
    status: "serving",
    called_at: "5:30 PM",
  },
  {
    id: "q-2",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_id: "doc-1",
    doctor_name: "Prof. Dr. M. A. Rahman",
    room_number: "Room 101",
    appointment_id: "apt-2",
    patient_name: "Sultana Razia",
    token_number: "A-013",
    status: "waiting",
  },
  {
    id: "q-3",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_id: "doc-2",
    doctor_name: "Dr. Farhana Yasmin",
    room_number: "Room 102",
    appointment_id: "apt-3",
    patient_name: "Nasrin Akhter",
    token_number: "B-007",
    status: "calling",
    called_at: "5:42 PM",
  },
  {
    id: "q-4",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_id: "doc-3",
    doctor_name: "Dr. Tanvir Ahmed",
    room_number: "Room 103",
    appointment_id: "apt-4",
    patient_name: "Haji Nurul Haque",
    token_number: "C-003",
    status: "serving",
    called_at: "5:25 PM",
  },
  {
    id: "q-5",
    organization_id: MOCK_ORGANIZATION.id,
    doctor_id: "doc-4",
    doctor_name: "Dr. Kazi Mahfuzur Rahman",
    room_number: "Room 104",
    appointment_id: "apt-5",
    patient_name: "Master Aayan Chowdhury",
    token_number: "D-005",
    status: "waiting",
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "apt-1",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "pat-1",
    patient_name: "Md. Rafiqul Islam",
    patient_phone: "01711-223344",
    doctor_id: "doc-1",
    doctor_name: "Prof. Dr. M. A. Rahman",
    appointment_date: "2026-09-12",
    time_slot: "05:00 PM - 07:00 PM",
    token_number: "A-012",
    source: "reception_walkin",
    status: "in_consultation",
    fee_status: "paid",
    created_at: "2026-09-12T16:15:00Z",
  },
  {
    id: "apt-2",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "pat-2",
    patient_name: "Nasrin Akhter",
    patient_phone: "01819-876543",
    doctor_id: "doc-2",
    doctor_name: "Dr. Farhana Yasmin",
    appointment_date: "2026-09-12",
    time_slot: "05:30 PM - 08:00 PM",
    token_number: "B-007",
    source: "online_web",
    status: "waiting",
    fee_status: "paid",
    created_at: "2026-09-12T14:30:00Z",
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv-1",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "pat-1",
    patient_name: "Md. Rafiqul Islam",
    patient_code: "OH-000101",
    patient_phone: "01711-223344",
    invoice_number: "INV-2026-0891",
    items: [
      {
        id: "item-1",
        item_type: "consultation",
        description: "OPD Consultation - Prof. Dr. M. A. Rahman",
        unit_price: 800,
        quantity: 1,
        total_price: 800,
      },
      {
        id: "item-2",
        item_type: "lab_test",
        description: "Complete Blood Count (CBC with ESR)",
        unit_price: 450,
        quantity: 1,
        total_price: 450,
      },
      {
        id: "item-3",
        item_type: "lab_test",
        description: "Blood Sugar Fasting (FBS)",
        unit_price: 150,
        quantity: 1,
        total_price: 150,
      },
    ],
    subtotal: 1400,
    discount_amount: 100,
    discount_percent: 7.14,
    discount_reason: "Special hospital discount approved by admin",
    discount_approved_by: "Admin",
    tax_amount: 0,
    total_amount: 1300,
    paid_amount: 1300,
    due_amount: 0,
    payment_status: "paid",
    payment_method: "cash",
    is_void: false,
    created_by_name: "Jewel Hossain (Cashier)",
    created_at: "2026-09-12T16:30:00Z",
  },
  {
    id: "inv-2",
    organization_id: MOCK_ORGANIZATION.id,
    patient_id: "pat-4",
    patient_name: "Haji Nurul Haque",
    patient_code: "OH-000104",
    patient_phone: "01611-998877",
    invoice_number: "INV-2026-0892",
    items: [
      {
        id: "item-4",
        item_type: "consultation",
        description: "Cardiology Consultation - Dr. Tanvir Ahmed",
        unit_price: 1000,
        quantity: 1,
        total_price: 1000,
      },
      {
        id: "item-5",
        item_type: "radiology",
        description: "Echocardiogram (2D Echo with Doppler)",
        unit_price: 2200,
        quantity: 1,
        total_price: 2200,
      },
      {
        id: "item-6",
        item_type: "lab_test",
        description: "Troponin-I (Quantitative)",
        unit_price: 1200,
        quantity: 1,
        total_price: 1200,
      },
    ],
    subtotal: 4400,
    discount_amount: 400,
    discount_percent: 9.09,
    discount_reason: "Senior Citizen concession",
    discount_approved_by: "Admin",
    tax_amount: 0,
    total_amount: 4000,
    paid_amount: 2500,
    due_amount: 1500,
    payment_status: "partially_paid",
    payment_method: "bkash",
    is_void: false,
    created_by_name: "Apon Mia (Accountant)",
    created_at: "2026-09-12T17:10:00Z",
  },
];

export const MOCK_LAB_TESTS: LabTest[] = [
  {
    id: "test-1",
    organization_id: MOCK_ORGANIZATION.id,
    category_id: "dept-6",
    category_name: "Hematology",
    name: "Complete Blood Count (CBC with ESR)",
    code: "CBC-01",
    price: 450,
    sample_type: "blood",
    delivery_hours: 4,
    reference_range: "Hb: 12-16 g/dL, WBC: 4000-11000/cumm",
  },
  {
    id: "test-2",
    organization_id: MOCK_ORGANIZATION.id,
    category_id: "dept-6",
    category_name: "Biochemistry",
    name: "Blood Sugar Fasting (FBS)",
    code: "FBS-01",
    price: 150,
    sample_type: "blood",
    delivery_hours: 3,
    unit: "mmol/L",
    reference_range: "3.9 - 6.0 mmol/L",
  },
  {
    id: "test-3",
    organization_id: MOCK_ORGANIZATION.id,
    category_id: "dept-6",
    category_name: "Biochemistry",
    name: "Serum Creatinine",
    code: "CREAT-01",
    price: 350,
    sample_type: "blood",
    delivery_hours: 4,
    unit: "mg/dL",
    reference_range: "0.6 - 1.2 mg/dL",
  },
  {
    id: "test-4",
    organization_id: MOCK_ORGANIZATION.id,
    category_id: "dept-6",
    category_name: "Biochemistry",
    name: "Lipid Profile (Cholesterol, Triglycerides, HDL, LDL)",
    code: "LIPID-01",
    price: 1100,
    sample_type: "blood",
    delivery_hours: 6,
    reference_range: "Cholesterol < 200 mg/dL",
  },
  {
    id: "test-5",
    organization_id: MOCK_ORGANIZATION.id,
    category_id: "dept-7",
    category_name: "Radiology",
    name: "Digital Chest X-Ray P/A View",
    code: "XRAY-01",
    price: 600,
    sample_type: "xray",
    delivery_hours: 2,
    reference_range: "Lungs clear, Cardiac silhouette normal",
  },
  {
    id: "test-6",
    organization_id: MOCK_ORGANIZATION.id,
    category_id: "dept-7",
    category_name: "Ultrasonography",
    name: "USG of Whole Abdomen with PVR",
    code: "USG-01",
    price: 1400,
    sample_type: "ultrasound",
    delivery_hours: 3,
  },
];

export const MOCK_LAB_ORDERS: LabOrder[] = [
  {
    id: "lab-ord-1",
    organization_id: MOCK_ORGANIZATION.id,
    order_number: "LAB-2026-0391",
    patient_id: "pat-1",
    patient_name: "Md. Rafiqul Islam",
    patient_code: "OH-000101",
    doctor_name: "Prof. Dr. M. A. Rahman",
    status: "completed",
    ordered_at: "2026-09-12T16:35:00Z",
    verified_by: "Dr. Lab In-Charge",
    tests: [
      {
        test_id: "test-1",
        test_name: "Complete Blood Count (CBC)",
        price: 450,
        status: "completed",
        result_value: "Hb: 13.8 g/dL, WBC: 7800, ESR: 14 mm/1st hr",
        normal_range: "Hb: 12-16, WBC: 4000-11000",
        is_abnormal: false,
      },
      {
        test_id: "test-2",
        test_name: "Blood Sugar Fasting (FBS)",
        price: 150,
        status: "completed",
        result_value: "7.8 mmol/L",
        normal_range: "3.9 - 6.0 mmol/L",
        unit: "mmol/L",
        is_abnormal: true,
        remarks: "Elevated Fasting Glucose. Suggestive of Diabetes.",
      },
    ],
  },
];

export const MOCK_MEDICINES: Medicine[] = [
  {
    id: "med-1",
    organization_id: MOCK_ORGANIZATION.id,
    brand_name: "Napa Extra",
    generic_name: "Paracetamol + Caffeine (500mg+65mg)",
    category: "Tablet",
    strength: "500mg+65mg",
    manufacturer: "Beximco Pharmaceuticals",
    current_stock: 1250,
    unit_price: 3.0,
    purchase_price: 2.4,
    reorder_level: 200,
    batches: [
      { batch_number: "BEX-9821", expiry_date: "2028-04-30", quantity: 1250 },
    ],
  },
  {
    id: "med-2",
    organization_id: MOCK_ORGANIZATION.id,
    brand_name: "Seclo 20",
    generic_name: "Omeprazole",
    category: "Capsule",
    strength: "20mg",
    manufacturer: "Square Pharmaceuticals",
    current_stock: 840,
    unit_price: 6.0,
    purchase_price: 4.8,
    reorder_level: 150,
    batches: [
      { batch_number: "SQ-4491", expiry_date: "2027-11-30", quantity: 840 },
    ],
  },
  {
    id: "med-3",
    organization_id: MOCK_ORGANIZATION.id,
    brand_name: "Ciprocin 500",
    generic_name: "Ciprofloxacin",
    category: "Tablet",
    strength: "500mg",
    manufacturer: "Square Pharmaceuticals",
    current_stock: 45,
    unit_price: 16.0,
    purchase_price: 13.0,
    reorder_level: 100, // Trigger low stock
    batches: [
      { batch_number: "SQ-1102", expiry_date: "2027-02-28", quantity: 45 },
    ],
  },
  {
    id: "med-4",
    organization_id: MOCK_ORGANIZATION.id,
    brand_name: "Monas 10",
    generic_name: "Montelukast",
    category: "Tablet",
    strength: "10mg",
    manufacturer: "Acme Laboratories",
    current_stock: 420,
    unit_price: 17.5,
    purchase_price: 14.2,
    reorder_level: 100,
    batches: [
      { batch_number: "ACM-7712", expiry_date: "2027-08-31", quantity: 420 },
    ],
  },
  {
    id: "med-5",
    organization_id: MOCK_ORGANIZATION.id,
    brand_name: "Inj. Ceftron 1g",
    generic_name: "Ceftriaxone IV/IM",
    category: "Injection",
    strength: "1g",
    manufacturer: "Square Pharmaceuticals",
    current_stock: 85,
    unit_price: 180.0,
    purchase_price: 145.0,
    reorder_level: 30,
    batches: [
      { batch_number: "SQ-9901", expiry_date: "2026-12-31", quantity: 85 },
    ],
  },
];

export const MOCK_BEDS: Bed[] = [
  { id: "bed-1", ward_name: "Male General Ward", bed_number: "MW-01", bed_type: "General", daily_rate: 600, status: "occupied", patient_name: "Abdul Karim", patient_code: "OH-000089", admitted_at: "2026-09-10" },
  { id: "bed-2", ward_name: "Male General Ward", bed_number: "MW-02", bed_type: "General", daily_rate: 600, status: "available" },
  { id: "bed-3", ward_name: "Male General Ward", bed_number: "MW-03", bed_type: "General", daily_rate: 600, status: "cleaning" },
  { id: "bed-4", ward_name: "Female General Ward", bed_number: "FW-01", bed_type: "General", daily_rate: 600, status: "occupied", patient_name: "Fatema Khatun", patient_code: "OH-000095", admitted_at: "2026-09-11" },
  { id: "bed-5", ward_name: "Female General Ward", bed_number: "FW-02", bed_type: "General", daily_rate: 600, status: "available" },
  { id: "bed-6", ward_name: "VIP Cabins (3rd Floor)", bed_number: "Cabin 301", bed_type: "Cabin AC", daily_rate: 3500, status: "occupied", patient_name: "Engr. Monirul Islam", patient_code: "OH-000078", admitted_at: "2026-09-09" },
  { id: "bed-7", ward_name: "VIP Cabins (3rd Floor)", bed_number: "Cabin 302", bed_type: "Cabin AC", daily_rate: 3500, status: "available" },
  { id: "bed-8", ward_name: "Deluxe Cabins (3rd Floor)", bed_number: "Cabin 305", bed_type: "Cabin Non-AC", daily_rate: 2200, status: "available" },
  { id: "bed-9", ward_name: "ICU Complex", bed_number: "ICU-01", bed_type: "ICU", daily_rate: 7500, status: "occupied", patient_name: "Sohrab Hossain", patient_code: "OH-000054", admitted_at: "2026-09-08" },
  { id: "bed-10", ward_name: "ICU Complex", bed_number: "ICU-02", bed_type: "ICU", daily_rate: 7500, status: "available" },
  { id: "bed-11", ward_name: "CCU Complex", bed_number: "CCU-01", bed_type: "CCU", daily_rate: 6500, status: "reserved", patient_name: "Haji Nurul Haque", patient_code: "OH-000104" },
  { id: "bed-12", ward_name: "CCU Complex", bed_number: "CCU-02", bed_type: "CCU", daily_rate: 6500, status: "available" },
];

export const MOCK_PRESCRIPTION: Prescription = {
  id: "rx-1",
  prescription_number: "RX-2026-0412",
  patient_id: "pat-1",
  patient_name: "Md. Rafiqul Islam",
  patient_age: 44,
  patient_gender: "Male",
  doctor_name: "Prof. Dr. M. A. Rahman",
  doctor_degrees: "MBBS, FCPS (Medicine), MACP (USA)",
  date: "12 Sep 2026",
  vitals: {
    bp: "130/85 mmHg",
    pulse: "76 bpm",
    weight: "72 kg",
    temp: "98.4 °F",
  },
  chief_complaints: [
    "Generalized weakness & fatigue for 3 weeks",
    "Occasional dizziness after fasting",
    "Mild lower back ache",
  ],
  diagnosis: ["Type-2 Diabetes Mellitus (Newly Detected)", "Mild Lumbar Strain"],
  medicines: [
    {
      name: "Tab. Metformin 500mg",
      dosage: "1 + 0 + 1",
      instruction: "After meal",
      duration: "1 month",
    },
    {
      name: "Tab. Seclo 20mg",
      dosage: "1 + 0 + 1",
      instruction: "30 mins before meal",
      duration: "14 days",
    },
    {
      name: "Tab. Napa Extra",
      dosage: "1 + 0 + 1",
      instruction: "After meal (if pain)",
      duration: "5 days",
    },
  ],
  advice:
    "Maintain strict diabetic diet (no direct sugar/sweets). Walk 40 minutes daily. Repeat FBS and 2h-ABF after 4 weeks.",
  next_visit: "10 Oct 2026",
};

export const MOCK_EMPLOYEES: Employee[] = [
  { id: "emp-1", employee_code: "EMP-001", full_name: "Jewel Hossain", department: "Accounts & Billing", designation: "Chief Accountant & Cashier", phone: "01711-001122", joining_date: "2023-01-15", basic_salary: 45000, status: "active" },
  { id: "emp-2", employee_code: "EMP-002", full_name: "Apon Mia", department: "Administration & Front Desk", designation: "Reception & Queue Manager", phone: "01722-112233", joining_date: "2023-03-01", basic_salary: 38000, status: "active" },
  { id: "emp-3", employee_code: "EMP-003", full_name: "Sharmin Sultana", department: "Nursing Staff", designation: "Senior Staff Nurse (ICU)", phone: "01733-223344", joining_date: "2023-06-10", basic_salary: 30000, status: "active" },
  { id: "emp-4", employee_code: "EMP-004", full_name: "Kazi Jahangir", department: "Pathology & Diagnostics", designation: "Senior Lab Technologist", phone: "01744-334455", joining_date: "2023-08-01", basic_salary: 35000, status: "active" },
];
