-- =====================================================================================
-- Migration: 20260922170000_erp_depth_payroll_lines_leaves_suppliers_pos.sql
-- Description:
--   ERP Depth Phase 58 — adds missing tables required for:
--   1. payroll_line_items  — per-employee payslip lines linked to payroll_runs
--   2. employee_leaves     — leave application and approval workflow
--   3. suppliers           — supplier register (if not already created by earlier migration)
--   4. purchase_orders     — formal PO header (if not already created)
--   5. purchase_order_items— PO line items (ensure table exists and has quantity_received)
--
--   All tables:
--     • Include organization_id FK → organizations (id) ON DELETE RESTRICT
--     • Enable RLS: ALTER TABLE ... ENABLE ROW LEVEL SECURITY
--     • RLS policy: authenticated sees own-org rows via private.get_current_org_id()
--     • REVOKE from PUBLIC/anon; GRANT to authenticated, service_role
-- =====================================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. payroll_line_items
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payroll_line_items (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID            NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
    payroll_run_id      UUID            NOT NULL REFERENCES public.payroll_runs(id) ON DELETE CASCADE,
    employee_id         UUID            NOT NULL REFERENCES public.employees(id) ON DELETE RESTRICT,
    month_year          VARCHAR(7)      NOT NULL,  -- 'YYYY-MM'
    gross_salary        NUMERIC(12, 2)  NOT NULL CHECK (gross_salary >= 0),
    deductions          NUMERIC(12, 2)  NOT NULL DEFAULT 0 CHECK (deductions >= 0),
    net_salary          NUMERIC(12, 2)  NOT NULL CHECK (net_salary >= 0),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    UNIQUE (organization_id, payroll_run_id, employee_id)
);

ALTER TABLE public.payroll_line_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY payroll_line_items_org_isolation ON public.payroll_line_items
    USING (organization_id = private.get_current_org_id());

REVOKE ALL ON public.payroll_line_items FROM PUBLIC;
REVOKE ALL ON public.payroll_line_items FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.payroll_line_items TO authenticated;
GRANT ALL ON public.payroll_line_items TO service_role;

CREATE INDEX IF NOT EXISTS idx_payroll_line_items_org_run   ON public.payroll_line_items (organization_id, payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_payroll_line_items_employee  ON public.payroll_line_items (organization_id, employee_id, month_year);

COMMENT ON TABLE  public.payroll_line_items IS 'Per-employee payslip lines generated by createPayrollRunAction';
COMMENT ON COLUMN public.payroll_line_items.net_salary IS 'Computed: gross_salary - deductions (always stored)';


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. employee_leaves
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.employee_leaves (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID            NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
    employee_id     UUID            NOT NULL REFERENCES public.employees(id) ON DELETE RESTRICT,
    leave_type      VARCHAR(20)     NOT NULL CHECK (leave_type IN ('ANNUAL', 'SICK', 'CASUAL', 'MATERNITY', 'UNPAID')),
    start_date      DATE            NOT NULL,
    end_date        DATE            NOT NULL,
    total_days      SMALLINT        NOT NULL CHECK (total_days > 0),
    reason          TEXT            NOT NULL,
    status          VARCHAR(10)     NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    approved_by     UUID,           -- references user_profiles(id), no FK to avoid schema ambiguity
    approved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    CONSTRAINT chk_leave_dates CHECK (end_date >= start_date)
);

ALTER TABLE public.employee_leaves ENABLE ROW LEVEL SECURITY;

CREATE POLICY employee_leaves_org_isolation ON public.employee_leaves
    USING (organization_id = private.get_current_org_id());

REVOKE ALL ON public.employee_leaves FROM PUBLIC;
REVOKE ALL ON public.employee_leaves FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.employee_leaves TO authenticated;
GRANT ALL ON public.employee_leaves TO service_role;

CREATE INDEX IF NOT EXISTS idx_employee_leaves_org_emp    ON public.employee_leaves (organization_id, employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_leaves_status     ON public.employee_leaves (organization_id, status);

COMMENT ON TABLE public.employee_leaves IS 'Employee leave applications with approval workflow';


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. suppliers
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.suppliers (
    id                   UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id      UUID           NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
    supplier_code        VARCHAR(20)    NOT NULL,
    company_name         VARCHAR(200)   NOT NULL,
    contact_person       VARCHAR(120),
    phone                VARCHAR(20)    NOT NULL,
    email                VARCHAR(120),
    address              TEXT,
    trade_license        VARCHAR(80),
    tin_vat              VARCHAR(40),
    payment_terms_days   SMALLINT       NOT NULL DEFAULT 30 CHECK (payment_terms_days >= 0),
    is_active            BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ    NOT NULL DEFAULT now(),
    UNIQUE (organization_id, supplier_code)
);

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY suppliers_org_isolation ON public.suppliers
    USING (organization_id = private.get_current_org_id());

REVOKE ALL ON public.suppliers FROM PUBLIC;
REVOKE ALL ON public.suppliers FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.suppliers TO authenticated;
GRANT ALL ON public.suppliers TO service_role;

CREATE INDEX IF NOT EXISTS idx_suppliers_org_active ON public.suppliers (organization_id, is_active);

COMMENT ON TABLE public.suppliers IS 'Vendor/supplier register with trade license and TIN/VAT details';


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. erp_purchase_orders
-- NOTE: Named erp_purchase_orders (not purchase_orders) to avoid conflict
-- with the pharmacy-specific purchase_orders table from 012_pharmacy.sql.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.erp_purchase_orders (
    id                      UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id         UUID           NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
    po_number               VARCHAR(40)    NOT NULL,
    supplier_id             UUID           NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,
    requisition_id          UUID           REFERENCES public.purchase_requisitions(id) ON DELETE SET NULL,
    status                  VARCHAR(20)    NOT NULL DEFAULT 'DRAFT'
                                CHECK (status IN ('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED')),
    order_date              DATE           NOT NULL DEFAULT CURRENT_DATE,
    expected_delivery_date  DATE,
    total_amount            NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    notes                   TEXT,
    created_at              TIMESTAMPTZ    NOT NULL DEFAULT now(),
    UNIQUE (organization_id, po_number)
);

ALTER TABLE public.erp_purchase_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY erp_purchase_orders_org_isolation ON public.erp_purchase_orders
    USING (organization_id = private.get_current_org_id());

REVOKE ALL ON public.erp_purchase_orders FROM PUBLIC;
REVOKE ALL ON public.erp_purchase_orders FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.erp_purchase_orders TO authenticated;
GRANT ALL ON public.erp_purchase_orders TO service_role;

CREATE INDEX IF NOT EXISTS idx_erp_purchase_orders_org_status   ON public.erp_purchase_orders (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_erp_purchase_orders_org_supplier ON public.erp_purchase_orders (organization_id, supplier_id);

COMMENT ON TABLE public.erp_purchase_orders IS 'ERP Formal Purchase Orders (not pharmacy-specific). Named erp_purchase_orders to avoid conflict.';


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. erp_purchase_order_items
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.erp_purchase_order_items (
    id                 UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id    UUID           NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
    po_id              UUID           NOT NULL REFERENCES public.erp_purchase_orders(id) ON DELETE CASCADE,
    item_name          VARCHAR(200)   NOT NULL,
    item_category      VARCHAR(80)    NOT NULL DEFAULT 'GENERAL',
    quantity_ordered   NUMERIC(10, 2) NOT NULL CHECK (quantity_ordered > 0),
    unit_price         NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
    total_price        NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (total_price >= 0),
    quantity_received  NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT chk_received_lte_ordered CHECK (quantity_received <= quantity_ordered)
);

ALTER TABLE public.erp_purchase_order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY erp_purchase_order_items_org_isolation ON public.erp_purchase_order_items
    USING (organization_id = private.get_current_org_id());

REVOKE ALL ON public.erp_purchase_order_items FROM PUBLIC;
REVOKE ALL ON public.erp_purchase_order_items FROM anon;
GRANT SELECT, INSERT, UPDATE ON public.erp_purchase_order_items TO authenticated;
GRANT ALL ON public.erp_purchase_order_items TO service_role;

CREATE INDEX IF NOT EXISTS idx_erp_po_items_org_po ON public.erp_purchase_order_items (organization_id, po_id);

COMMENT ON TABLE public.erp_purchase_order_items IS 'ERP Purchase Order line items linked to erp_purchase_orders';


-- NOTE: The legacy purchase_order_items table from 012_pharmacy.sql is NOT modified.
-- It handles pharmacy medicine purchase orders only.
-- ERP general procurement uses erp_purchase_order_items (created above).
